// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjX7QQoEmXdAzsBbUYUoZDut8QMviEhOg',
    appId: '1:889154003517:web:55d6f8418f9a2339468054',
    messagingSenderId: '889154003517',
    projectId: 'fir-tutorial-70f36',
    authDomain: 'fir-tutorial-70f36.firebaseapp.com',
    storageBucket: 'fir-tutorial-70f36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAssyc6YobnU6U4yCS_XBHtoUucQyCFEPw',
    appId: '1:889154003517:android:9a3d2b1008c71140468054',
    messagingSenderId: '889154003517',
    projectId: 'fir-tutorial-70f36',
    storageBucket: 'fir-tutorial-70f36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmxmadbctN9EqTOoyRKxyhdN8BpTGPydI',
    appId: '1:889154003517:ios:62982ffcd8860837468054',
    messagingSenderId: '889154003517',
    projectId: 'fir-tutorial-70f36',
    storageBucket: 'fir-tutorial-70f36.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjX7QQoEmXdAzsBbUYUoZDut8QMviEhOg',
    appId: '1:889154003517:web:ef64e364d04b51fd468054',
    messagingSenderId: '889154003517',
    projectId: 'fir-tutorial-70f36',
    authDomain: 'fir-tutorial-70f36.firebaseapp.com',
    storageBucket: 'fir-tutorial-70f36.firebasestorage.app',
  );
}
